# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacritty = {
    pname = "alacritty";
    version = "b27ecc36ec9cacddfff0f3963af00a5b52d1cf02";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "alacritty";
      rev = "b27ecc36ec9cacddfff0f3963af00a5b52d1cf02";
      fetchSubmodules = false;
      sha256 = "sha256-7kv1x0MBdc1QPoaO1mXhTjMRLNDagPh3Kw4YQhFXo+Q=";
    };
    date = "2025-03-11";
  };
  base16 = {
    pname = "base16";
    version = "67fc690d16dea7bed0eb80a62a6cb0619d3c2a88";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "base16";
      rev = "67fc690d16dea7bed0eb80a62a6cb0619d3c2a88";
      fetchSubmodules = false;
      sha256 = "sha256-1UZmQ0S+1UTA4AR47Ko9ZHDoPMuU5vfjN912pYqqpnk=";
    };
    date = "2025-03-11";
  };
  dunst = {
    pname = "dunst";
    version = "9c97729c4175a014bc04cf83db45eda7fb287ff5";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "dunst";
      rev = "9c97729c4175a014bc04cf83db45eda7fb287ff5";
      fetchSubmodules = false;
      sha256 = "sha256-7SiKrYv4ULp/gqgCwGurxWiG4wE7vAhSadtVzpiSqyM=";
    };
    date = "2025-03-11";
  };
  iterm = {
    pname = "iterm";
    version = "f29f68d7dd2ce1d4a94f34f2aa9a6294d95d28da";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "iterm";
      rev = "f29f68d7dd2ce1d4a94f34f2aa9a6294d95d28da";
      fetchSubmodules = false;
      sha256 = "sha256-KncTFP2jkCTNsM6IMDLb0u+Jdk62UcC+i5AO/LDU6Rg=";
    };
    date = "2025-03-11";
  };
  kitty = {
    pname = "kitty";
    version = "ce2a550d02509cb180dbb7bea99f3e6a43095cad";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "kitty";
      rev = "ce2a550d02509cb180dbb7bea99f3e6a43095cad";
      fetchSubmodules = false;
      sha256 = "sha256-Hu2Ptg/k31f46FMfnOqw0XI8LiCnDCkcvFn++DcpUN8=";
    };
    date = "2025-03-11";
  };
  lazygit = {
    pname = "lazygit";
    version = "ed2f96b1c9c1b479ed0304e91de01725c55ea860";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "lazygit";
      rev = "ed2f96b1c9c1b479ed0304e91de01725c55ea860";
      fetchSubmodules = false;
      sha256 = "sha256-0LRwuZYkx7DgCrG7R18RGu2LdOYmC9lOD1Dv5v8QfZI=";
    };
    date = "2025-03-11";
  };
  scss = {
    pname = "scss";
    version = "474dfb8f10bec9b4fdeb8e0b2406276f5414fb9a";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "scss";
      rev = "474dfb8f10bec9b4fdeb8e0b2406276f5414fb9a";
      fetchSubmodules = false;
      sha256 = "sha256-Prv87KOR461sjz131uUeFr7ZDL3hHfS4xiegNsNhgFY=";
    };
    date = "2025-03-11";
  };
  tmux = {
    pname = "tmux";
    version = "906b94e0d1a9db274f8abeac1a99cffa0c46355d";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "tmux";
      rev = "906b94e0d1a9db274f8abeac1a99cffa0c46355d";
      fetchSubmodules = false;
      sha256 = "sha256-IbcqSrO+R4xuWC1kypcGToslFUmG5igEmIkFhEjg9sg=";
    };
    date = "2025-03-11";
  };
}
