# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacritty = {
    pname = "alacritty";
    version = "4a01f85ad58caa57f030f0fcb032c2c001ba221d";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "alacritty";
      rev = "4a01f85ad58caa57f030f0fcb032c2c001ba221d";
      fetchSubmodules = false;
      sha256 = "sha256-KQFJbTLVfpqWv2B4CW+niit9edv6/auVJOAtS6a+GTc=";
    };
    date = "2025-03-12";
  };
  base16 = {
    pname = "base16";
    version = "bb35ccfac371526f0c672643db151b15b4c59ee7";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "base16";
      rev = "bb35ccfac371526f0c672643db151b15b4c59ee7";
      fetchSubmodules = false;
      sha256 = "sha256-IxrCNtNPkuNkwX2uM3laa1FWFEm+cv/Jnq8eQOi1Rds=";
    };
    date = "2025-03-12";
  };
  dunst = {
    pname = "dunst";
    version = "0bcc1c6165abfd9e4ea0807d043854a1e008956c";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "dunst";
      rev = "0bcc1c6165abfd9e4ea0807d043854a1e008956c";
      fetchSubmodules = false;
      sha256 = "sha256-/lRvNmed6O6dKzUNdVv7LsmbmV4Bsd3DpaxraNsUv28=";
    };
    date = "2025-03-12";
  };
  iterm = {
    pname = "iterm";
    version = "8cbc18642aa5eb13a780e5b8e89feb520b27eff5";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "iterm";
      rev = "8cbc18642aa5eb13a780e5b8e89feb520b27eff5";
      fetchSubmodules = false;
      sha256 = "sha256-RQrSWWLGSum6CHy4M6Zxugd73EjACCOcxD6ofH6a9GA=";
    };
    date = "2025-03-12";
  };
  kitty = {
    pname = "kitty";
    version = "d8664b36e9bbfab3115ae416ab65e72f765647ae";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "kitty";
      rev = "d8664b36e9bbfab3115ae416ab65e72f765647ae";
      fetchSubmodules = false;
      sha256 = "sha256-lHrEzsQtUJ+tCQ8avu6Pq0tVej+MDrCos37ylnqxH6Y=";
    };
    date = "2025-03-12";
  };
  lazygit = {
    pname = "lazygit";
    version = "ed2f96b1c9c1b479ed0304e91de01725c55ea860";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "lazygit";
      rev = "ed2f96b1c9c1b479ed0304e91de01725c55ea860";
      fetchSubmodules = false;
      sha256 = "sha256-0LRwuZYkx7DgCrG7R18RGu2LdOYmC9lOD1Dv5v8QfZI=";
    };
    date = "2025-03-11";
  };
  scss = {
    pname = "scss";
    version = "bdabcb7e12ba9facbb191e1bf1443d04dbb3229e";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "scss";
      rev = "bdabcb7e12ba9facbb191e1bf1443d04dbb3229e";
      fetchSubmodules = false;
      sha256 = "sha256-ZnCFA5MH/TvdMGXxLidOlwbgwOQTMz3fOqJ1BJGqVN8=";
    };
    date = "2025-03-12";
  };
  tmux = {
    pname = "tmux";
    version = "92755a85e5bafc72414265eb053474fbf30badc3";
    src = fetchFromGitHub {
      owner = "everviolet";
      repo = "tmux";
      rev = "92755a85e5bafc72414265eb053474fbf30badc3";
      fetchSubmodules = false;
      sha256 = "sha256-3ku6JA5spb3Eru/n3sKyKti0MEnxHDOsBJsAfA/Uh7o=";
    };
    date = "2025-03-12";
  };
}
